name: infinite_scroll_pagination
description: "Este projeto é uma alteração do projeto original de: https://github.com/EdsonBueno/infinite_scroll_pagination"
version: 3.2.3
homepage: https://github.com/renatolealdev/infinite_scroll_for_chat_necessities

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.22.0'

dependencies:
  flutter:
    sdk: flutter
  sliver_tools: ^0.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.9
  test: ^1.16.5
